### ISSUE TITLE
WorksheetStart error

### ISSUE THREAD

**Issue by gambledor** [HerringtonDarkholme/vim-worksheet#1] opened 2014-09-26 09:57 UTC
Error detected while processing function <SNR>104_worksheet_start:
line   31:
No worksheet REPL found for
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "..../vimrc/bundle/vim-worksheet/plugin/worksheet.py", line 86, in make_sheet
    ret = self.repl.correspond(source)
AttributeError: WorksheetCommand instance has no attribute 'repl'

**Comment by HerringtonDarkholme** [comment] 2014-09-26 09:59
Thanks for your trying out Vim-worksheet.

Would you please provide more information? I cannot tell anything from this error message.

Vim version, File type, python version, system command and PATH environment will help.

**Comment by gambledor** [comment] 2014-09-26 10:20
After your comment I understood I had to start it from an already opened file.
I started it from a php opened file and this is ok.
After that vim doesn't recognize the commands: WorksheetEval, WorksheetClean and WorksheetEnd; it keeps to say "E492: Not an editor command: ..."
Vim version: MacVim 7.4
filetype=php
python version = 2.7.5
PATH = bash: /opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/opt/ImageMagick/bin

**Comment by HerringtonDarkholme** [comment] 2014-09-26 10:23
Thanks for feedback, I'll add filetype check in it.

**Comment by HerringtonDarkholme** [comment] 2014-09-26 13:00
fixed in 1d871365601c180eeda81367fee3c374d2731cfd

**Comment by gambledor** [comment] 2014-09-26 13:09
I'm sorry by now I get the following error

Error detected while processing function <SNR>104_worksheet_start:
line   37:
Could not start php -a
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/Users/xxx/tmp/vimrc/bundle/vim-worksheet/plugin/worksheet.py", line 105, in make_sheet
    ret = self.repl.correspond(source)
AttributeError: WorksheetCommand instance has no attribute 'repl'

**Comment by HerringtonDarkholme** [comment] 2014-09-26 14:51
It seems vim-worksheet cannot start php. Can you start `php -a` in your terminal? 
Is vim started in another profile so that it cannot find php?
Hope it will helps you to find the problem

**Comment by gambledor** [comment] 2014-09-26 14:57
I understood the same but php -a starts inside vim by :!php -a and from my terminal too. 
Thus I thought the problem could be inside the plugin.

**Comment by HerringtonDarkholme** [comment] 2014-09-26 15:21
It works finely on my Linux machine. I can test on mac when I come back to my workplace.

By the way, vim-worksheet uses regular expression to distinguish REPL result. When it fails to find the pattern for a language, the plugin treats this as failing to start REPL.

Have you ever started this plugin, and saw the outpu? What's your PHP prompt?

The regex for PHP file is `''(php|>>>) [>{\\('\"] "` in Python's regexp flavor.

**Comment by gambledor** [comment] 2014-09-26 15:26
This is my php prompt
$ php -a
Interactive shell

php >

**Comment by HerringtonDarkholme** [comment] 2014-09-26 15:34
It should work. I think I need to get a MacVim to debug it, after I can get a Mac.

Try to launch mvim in terminal and give a another try? I tested this plugin in terminal vim on Mac.

How to mapping vim to mvim binary :
http://superuser.com/a/334253

**Comment by HerringtonDarkholme** [comment] 2014-09-27 06:10
I reproduced your problem on my Windows machine, by scala. It seems scala REPL responded too slow to be caught within vim-worksheet's timeout (10s).

Can you start php -a fast?

I think I will add configuration to this plugin.

**Comment by HerringtonDarkholme** [comment] 2014-09-28 01:28
Sorry, I cannot reproduce your problem on MacVim.

**Comment by HerringtonDarkholme** [comment] 2015-10-10 17:21
Close due to no further feedback

**Closed as completed by HerringtonDarkholme** 2015-10-10 17:21 UTC
